@AddMember_HostAddress = http://localhost:8080

POST {{AddMember_HostAddress}}/addmember?name=Carlos&lastname=Garcia&birthyear=2020
Content-Type: application/json
Accept: application/json

###

POST {{AddMember_HostAddress}}/addmember?name=kevin&lastname=Suarez&birthyear=1995
Content-Type: application/json
Accept: application/json

###

