@AddMember_HostAddress = http://localhost:8080

POST {{AddMember_HostAddress}}/addmember?name=Carlos&lastname=Garcia&birthyear=2020
Content-Type: application/json
Accept: application/json

###

POST {{AddMember_HostAddress}}/addmember?name=Oscarr2&lastname=Garcia&birthyear=1966
Content-Type: application/json
Accept: application/json

###

