@GetAdults_HostAddress = http://localhost:8080
@Docker_HostAddress = http://localhost:5001

GET {{GetAdults_HostAddress}}/Children/
Accept: application/json

###
GET {{Docker_HostAddress}}/Children/
Accept: application/json
